runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  secure: always
  static_files: dist/CarFleetManagementSystem/index.html
  upload: dist/CarFleetManagementSystem/.*
- url: /(.*\.js)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  upload: dist/CarFleetManagementSystem/.*\.js
- url: /(.*\.css)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  mime_type: text/css
  upload: dist/CarFleetManagementSystem/.*\.css
- url: /.*
  secure: always
  static_files: dist/CarFleetManagementSystem/index.html
  upload: dist/CarFleetManagementSystem/.*
- url: /(.*\.png)
  secure: always
  static_files: dist/CarFleetManagementSystem/\1
  upload: dist/CarFleetManagementSystem/.*\.png
- url: /(.*\.json)
  secure: always
  static_files: dist/CarFleetManagementSystem/\1
  upload: dist/CarFleetManagementSystem/.*\.json 
skip_files:
 - e2e/
 - node_modules/
 - src/
 - ^(.*/)?\..*$
 - ^(.*/)?.*\.md$
 - ^(.*/)?.*\.yaml$
 - ^LICENSE