runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  secure: always
  static_files: dist/CarFleetManagementSystem/index.html
  upload: dist/CarFleetManagementSystem/.*
- url: /(.*\.js)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  upload: dist/CarFleetManagementSystem/.*\.js
- url: /(.*\.css)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  mime_type: text/css
  upload: dist/CarFleetManagementSystem/.*\.css
- url: /(.*\.json)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  mime_type: application/json
  upload: dist/CarFleetManagementSystem/.*\.json
- url: /(.*\.png)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  mime_type: image/png
  upload: dist/CarFleetManagementSystem/.*\.png
- url: /(.*\.jpg)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  mime_type: image/jpeg
  upload: dist/CarFleetManagementSystem/.*\.jpg
- url: /(.*\.ico)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  mime_type: image/x-icon
  upload: dist/CarFleetManagementSystem/.*\.ico
- url: /(.*\.(svg|svgz))
  secure: always
  redirect_http_response_code: 301
  static_files: dist/CarFleetManagementSystem/\1
  mime_type: images/svg+xml
  upload: dist/CarFleetManagementSystem/(.*\.(svg|svgz))
- url: /.*
  secure: always
  static_files: dist/CarFleetManagementSystem/index.html
  upload: dist/CarFleetManagementSystem/.*
skip_files:
 - e2e/
 - node_modules/
 - src/
 - ^(.*/)?\..*$
 - ^(.*/)?.*\.md$
 - ^(.*/)?.*\.yaml$
 - ^LICENSE
