runtime: python27
api_version: 1
threadsafe: true
handlers:
- url: /
  secure: always
  static_files: dist/CarFleetManagementSystem/index.html
  upload: dist/CarFleetManagementSystem/index.html
- url: /
  secure: always
  static_dir: dist/CarFleetManagementSystem 
skip_files:
 - e2e/
 - node_modules/
 - src/
 - ^(.*/)?\..*$
 - ^(.*/)?.*\.json$
 - ^(.*/)?.*\.md$
 - ^(.*/)?.*\.yaml$
 - ^LICENSE